<div class="legal">
  <a href="/" class="back-link">← Back to The Stayman Whisperer</a>

  <h1>Terms of Service</h1>
  <p class="updated">Last updated: March 28, 2026</p>

  <p>Welcome to The Stayman Whisperer ("Service", "we", "us", "our"). By creating an account or using our Service, you agree to these Terms of Service ("Terms"). Please read them carefully.</p>

  <h2>1. Service Description</h2>
  <p>The Stayman Whisperer is an AI-powered bridge analysis tool that provides bidding advice, opening lead recommendations, card play guidance, and post-mortem hand analysis. Our analysis is generated by Anthropic's Claude AI and is intended for educational and recreational purposes.</p>

  <h2>2. Account Requirements</h2>
  <ul>
    <li>You must provide a valid email address and verify it before accessing the Service.</li>
    <li>You must be at least 13 years old to create an account.</li>
    <li>You are responsible for maintaining the security of your account credentials.</li>
    <li>You may not create multiple accounts to circumvent usage limits.</li>
    <li>Account access may require approval by an administrator.</li>
  </ul>

  <h2>3. Acceptable Use</h2>
  <p>You agree not to:</p>
  <ul>
    <li>Use the Service for any illegal or unauthorized purpose.</li>
    <li>Attempt to access the Service through automated means (bots, scrapers, etc.) beyond the provided Chrome extension.</li>
    <li>Resell, redistribute, or commercially exploit the AI-generated analysis.</li>
    <li>Attempt to reverse engineer, decompile, or extract the underlying prompts or algorithms.</li>
    <li>Abuse the Service by submitting excessive, malicious, or non-bridge-related queries.</li>
    <li>Interfere with or disrupt the Service or its infrastructure.</li>
    <li>Share your account credentials with others.</li>
  </ul>

  <h2>4. AI-Generated Content Disclaimer</h2>
  <p><strong>The analysis provided by this Service is generated by artificial intelligence and may contain errors, inaccuracies, or suboptimal recommendations.</strong></p>
  <ul>
    <li>AI-generated bridge analysis is not a substitute for professional bridge instruction or tournament direction.</li>
    <li>We do not guarantee the accuracy, completeness, or reliability of any analysis.</li>
    <li>Analysis may vary for the same hand depending on how it is presented.</li>
    <li>You should use your own judgment when making decisions based on our analysis.</li>
    <li>We are not responsible for any losses or outcomes resulting from following AI-generated advice.</li>
  </ul>

  <h2>5. Subscription and Billing</h2>
  <h3>Free Tier</h3>
  <ul>
    <li>Free accounts receive a limited number of analyses per day (currently 10).</li>
    <li>Daily limits reset at midnight UTC.</li>
    <li>We may adjust free tier limits at any time.</li>
  </ul>
  <h3>Pro Tier ($3/month)</h3>
  <ul>
    <li>Pro subscriptions are billed monthly at $3.00 USD via Stripe.</li>
    <li>Pro accounts receive an increased daily analysis limit (currently 50).</li>
    <li>Subscriptions auto-renew unless canceled before the next billing cycle.</li>
    <li>You may cancel your subscription at any time through the billing portal.</li>
    <li>Cancellation takes effect at the end of the current billing period.</li>
    <li>We do not offer prorated refunds for partial months.</li>
    <li>If payment fails, your account may be downgraded to the Free tier after a grace period.</li>
  </ul>
  <h3>Refunds</h3>
  <p>Refund requests may be considered on a case-by-case basis within 7 days of a charge. Contact us to request a refund.</p>

  <h2>6. Intellectual Property</h2>
  <ul>
    <li>You retain ownership of any bridge hand data you submit to the Service.</li>
    <li>AI-generated analysis is provided for your personal use and may be shared via the built-in sharing feature.</li>
    <li>The Service's design, code, branding, and documentation are our intellectual property.</li>
    <li>The Chrome extension is provided for personal use in connection with the Service.</li>
  </ul>

  <h2>7. Data Usage</h2>
  <p>By using the Service, you acknowledge that:</p>
  <ul>
    <li>Bridge hand data and prompts are sent to Anthropic's Claude API for analysis.</li>
    <li>We store your analysis history to provide the history feature.</li>
    <li>Usage data (query counts, token usage) is tracked for rate limiting and billing.</li>
    <li>See our <a href="/privacy">Privacy Policy</a> for full details on data collection and usage.</li>
  </ul>

  <h2>8. Rate Limits and Service Availability</h2>
  <ul>
    <li>Usage is subject to daily rate limits based on your tier.</li>
    <li>The Service depends on third-party APIs (Anthropic Claude) and may experience downtime or degraded performance.</li>
    <li>We do not guarantee 100% uptime or availability.</li>
    <li>We may implement additional rate limits or usage restrictions to maintain service quality.</li>
  </ul>

  <h2>9. Account Termination</h2>
  <ul>
    <li>You may delete your account at any time by contacting us.</li>
    <li>We may suspend or terminate accounts that violate these Terms.</li>
    <li>We may suspend accounts with unpaid balances or fraudulent payment activity.</li>
    <li>Upon termination, your analysis history and account data may be deleted.</li>
    <li>Active subscriptions will be canceled upon account termination.</li>
  </ul>

  <h2>10. Limitation of Liability</h2>
  <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
  <ul>
    <li>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.</li>
    <li>WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.</li>
    <li>OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.</li>
    <li>WE ARE NOT LIABLE FOR LOSSES RESULTING FROM AI-GENERATED ANALYSIS OR RECOMMENDATIONS.</li>
  </ul>

  <h2>11. Indemnification</h2>
  <p>You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.</p>

  <h2>12. Changes to Terms</h2>
  <p>We may update these Terms from time to time. When we do:</p>
  <ul>
    <li>We will update the "Last updated" date at the top of this page.</li>
    <li>For material changes, we will notify you via email.</li>
    <li>Continued use of the Service after changes constitutes acceptance of the new Terms.</li>
  </ul>

  <h2>13. Governing Law</h2>
  <p>These Terms are governed by the laws of the United States. Any disputes will be resolved through binding arbitration in accordance with applicable rules.</p>

  <h2>14. Contact</h2>
  <p>If you have questions about these Terms, please use the Feedback form in the application or contact us via email.</p>
</div>

<style>
  .legal {
    max-width: 700px; margin: 0 auto; padding: 40px 20px;
    color: #b0c8b0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    line-height: 1.7; font-size: 14px;
  }
  .back-link { color: #d4af37; text-decoration: none; font-size: 13px; display: inline-block; margin-bottom: 24px; }
  .back-link:hover { text-decoration: underline; }
  h1 { font-size: 28px; color: #d4af37; margin: 0 0 8px; }
  .updated { font-size: 12px; color: #6a8a6a; margin-bottom: 28px; }
  h2 { font-size: 18px; color: #c0d8c0; margin: 28px 0 12px; border-bottom: 1px solid #1a2a1a; padding-bottom: 6px; }
  h3 { font-size: 15px; color: #a0b8a0; margin: 16px 0 8px; }
  p { margin: 0 0 12px; }
  ul { margin: 0 0 12px; padding-left: 24px; }
  li { margin-bottom: 6px; }
  a { color: #d4af37; }
  strong { color: #e0c860; }
</style>
